version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        links:
            - php
        restart: always
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www
        restart: always